[package]
name = "torb"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.3.0"
dirs = "1.0.4"
ureq = "2.5.0"
clap = { version = "3.1.6", features = ["derive"] }
serde = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"