[package]
name = "torb"
version = "0.1.0"
edition = "2021"
include = ["/build_files"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
